# Рекомендательные системы
## Programming assignment

***Oписание задачи:***

Небольшой интернет-магазин попросил вас добавить ранжирование товаров в блок "Смотрели ранее" - в нем теперь надо показывать не последние просмотренные пользователем товары, а те товары из просмотренных, которые он наиболее вероятно купит. Качество вашего решения будет оцениваться по количеству покупок в сравнении с прошлым решением в ходе А/В теста, т.к. по доходу от продаж статзначимость будет достигаться дольше из-за разброса цен. Таким образом, ничего заранее не зная про корреляцию оффлайновых и онлайновых метрик качества, в начале проекта вы можете лишь постараться оптимизировать **recall@k** и **precision@k**.

Это задание посвящено построению простых бейзлайнов для этой задачи: ранжирование просмотренных товаров по частоте просмотров и по частоте покупок. Эти бейзлайны, с одной стороны, могут помочь вам грубо оценить возможный эффект от ранжирования товаров в блоке - например, чтобы вписать какие-то числа в коммерческое предложение заказчику, а с другой стороны, могут оказаться самым хорошим вариантом, если данных очень мало (недостаточно для обучения даже простых моделей).

In [115]:
import pandas as pd
import numpy as np
from __future__ import division

In [116]:
train_data = pd.read_csv('coursera_sessions_train.txt', sep=';', names=['viewed', 'purchased'])
test_data = pd.read_csv('coursera_sessions_test.txt', sep=';', names=['viewed', 'purchased'])

***Входные данные***

Вам дается две выборки с пользовательскими сессиями - **id**-шниками просмотренных и **id**-шниками купленных товаров. Одна выборка будет использоваться для обучения (оценки популярностей товаров), а другая - для теста.

В файлах записаны сессии по одной в каждой строке. Формат сессии: **id** просмотренных товаров через , затем идёт ; после чего следуют id купленных товаров (если такие имеются), разделённые запятой. Например, **1,2,3,4**; или **1,2,3,4;5,6**.

Гарантируется, что среди **id** купленных товаров все различные.

***Важно:***

- Сессии, в которых пользователь ничего не купил, исключаем из оценки качества.
- Если товар не встречался в обучающей выборке, его популярность равна 0.
- Рекомендуем разные товары. И их число должно быть не больше, чем количество различных просмотренных пользователем товаров.
- Рекомендаций всегда не больше, чем минимум из двух чисел: количество просмотренных пользователем товаров и **k** в **recall@k / precision@k.**

**Задание:**

1. На обучении постройте частоты появления **id** в просмотренных и в купленных (**id** может несколько раз появляться в просмотренных, все появления надо учитывать)
2. Реализуйте два алгоритма рекомендаций:
    - сортировка просмотренных **id** по популярности (частота появления в просмотренных),
    - сортировка просмотренных **id** по покупаемости (частота появления в покупках).
3. Для данных алгоритмов выпишите через пробел **AverageRecall@1**, **AveragePrecision@1**, **AverageRecall@5**, **AveragePrecision@5** на обучающей и тестовых выборках, округляя до 2 знака после запятой. Это будут ваши ответы в этом задании. Посмотрите, как они соотносятся друг с другом. Где качество получилось выше? Значимо ли это различие? Обратите внимание на различие качества на обучающей и тестовой выборке в случае рекомендаций по частотам покупки.

Если частота одинаковая, то сортировать нужно по возрастанию момента просмотра (чем раньше появился в просмотренных, тем больше приоритет)

In [318]:
from collections import OrderedDict, Counter


viewed = OrderedDict()
for session in train_data['viewed']:
    for product in session.split(','):
        viewed[product] = viewed.get(product, 0) + 1 

for session in test_data.dropna()['viewed'].values:
    for product in session.split(','):
        if product not in viewed:
            viewed[product] = 0
        elif product not in purchased:
            purchased[product] = 0
                   
purchased = OrderedDict()
for session in train_data.dropna()['purchased']:
    for product in session.split(','):
        purchased[product] = purchased.get(product, 0) + 1

In [315]:
is_viewed = []
for session in train_data['viewed'].values:
    for product in session.split(','):
        is_viewed_train.append(product)

In [335]:
is_viewed_test = []
for session in test_data['viewed'].values:
    for product in session.split(','):
        is_viewed_test.append(product)

In [369]:
for product in is_viewed:
    if product not in purchased:
        purchased[product] = 0

In [336]:
for product in is_viewed_test:
    if product not in purchased:
        purchased[product] = 0

In [328]:
purchased['70']

KeyError: '70'

In [119]:
sorted_train_viewed = []
sorted_train_purchased = []
for idx in train_data.dropna()['viewed'].values:
    sorted_train_viewed.append(sorted(set(idx.split(',')), key=lambda idx: viewed[idx], reverse=True))
    sorted_train_purchased.append(sorted(set(idx.split(',')), key=lambda idx: purchased[idx], reverse=True))

In [321]:
sorted_train_purchased = []
for idx in train_data.dropna()['viewed'].values:
    sorted_train_purchased.append(sorted(set(idx.split(',')), key=lambda idx: (purchased[idx], train_order[idx]), reverse=True))

In [373]:
sorted_test_purchased = []
for idx in test_data.dropna()['viewed'].values:
    sorted_test_purchased.append(sorted(set(idx.split(',')), key=lambda idx: (purchased[idx], test_order[idx]), reverse=True))

In [372]:
train_order

{'50088': 16,
 '58146': 16,
 '44884': 14,
 '13356': 16,
 '73399': 15,
 '99682': 15,
 '11542': 19,
 '11543': 18,
 '11540': 19,
 '11541': 20,
 '11546': 15,
 '11547': 14,
 '11544': 17,
 '11545': 16,
 '89378': 14,
 '89379': 13,
 '11548': 19,
 '11549': 19,
 '91138': 19,
 '5988': 20,
 '19399': -17,
 '19398': -15,
 '5982': 11,
 '19396': -13,
 '5980': 13,
 '5981': 12,
 '5986': 19,
 '5987': 18,
 '19391': -7,
 '5985': 20,
 '73393': 13,
 '82449': 16,
 '82448': 17,
 '72706': 20,
 '73392': 20,
 '82443': 11,
 '36602': 20,
 '82441': 13,
 '82440': 14,
 '82447': 18,
 '82446': 19,
 '82445': 20,
 '82444': 20,
 '57481': 11,
 '57480': 12,
 '83894': 13,
 '57483': 18,
 '2555': 20,
 '57485': 18,
 '73394': 20,
 '72628': 17,
 '82991': 20,
 '82990': 18,
 '82993': 20,
 '82992': 20,
 '88391': 19,
 '88390': 20,
 '46139': 17,
 '46138': 18,
 '46137': 19,
 '46136': 20,
 '46135': 16,
 '46134': 18,
 '46133': 20,
 '46132': 18,
 '46131': 20,
 '46130': 19,
 '72704': 20,
 '36706': 6,
 '89374': 19,
 '97150': 20,
 '89375': 18,
 '89376': 16,
 '89377': 15,
 '60834': 17,
 '270': 15,
 '271': 14,
 '272': 13,
 '273': 12,
 '274': 11,
 '275': 10,
 '276': 9,
 '277': 8,
 '278': 7,
 '279': 6,
 '19979': 17,
 '19978': 18,
 '16701': 12,
 '16700': 13,
 '16702': 11,
 '88023': 20,
 '88022': 18,
 '88021': 19,
 '88020': 20,
 '12019': 15,
 '12018': 16,
 '42086': 20,
 '12015': 20,
 '12014': 20,
 '12017': 17,
 '12016': 19,
 '12011': 19,
 '12010': 20,
 '12013': 19,
 '12012': 20,
 '17258': 16,
 '17259': 15,
 '64676': 16,
 '64677': 15,
 '64670': 20,
 '64671': 20,
 '100011': 16,
 '52460': 20,
 '17251': 20,
 '17252': 18,
 '17253': 20,
 '17254': 20,
 '17255': 19,
 '17256': 18,
 '17257': 17,
 '63024': 18,
 '63025': 20,
 '10709': 20,
 '10708': 20,
 '63020': 20,
 '46702': 20,
 '9258': 20,
 '9259': 19,
 '10703': 20,
 '9257': 20,
 '9254': 18,
 '9255': 20,
 '9252': 15,
 '9253': -3,
 '9250': 18,
 '10704': 19,
 '46793': 20,
 '101352': 19,
 '91132': 20,
 '21619': 10,
 '21618': 11,
 '101353': 18,
 '21615': 14,
 '21614': 16,
 '21617': 12,
 '21616': 13,
 '21611': 20,
 '49560': 18,
 '21613': 17,
 '21612': 19,
 '80275': 14,
 '80272': 17,
 '79230': 13,
 '80273': 16,
 '69170': 18,
 '19397': -14,
 '69172': 15,
 '69173': 13,
 '69174': 16,
 '80270': 19,
 '45448': 17,
 '45449': 16,
 '45446': 19,
 '45447': 18,
 '45444': 20,
 '45445': 20,
 '91076': 16,
 '19395': -12,
 '45440': 20,
 '45441': 17,
 '44799': 20,
 '44798': 20,
 '54540': 17,
 '19394': -11,
 '20150': 19,
 '44791': 17,
 '19393': -10,
 '44793': 18,
 '44792': 0,
 '44795': 20,
 '91130': 17,
 '19392': -8,
 '46869': 18,
 '58079': 10,
 '5984': 16,
 '58075': 20,
 '48625': 20,
 '58077': 13,
 '19390': -6,
 '46865': 20,
 '58070': 17,
 '46867': 20,
 '58072': 19,
 '29236': 20,
 '32836': 20,
 '48627': 19,
 '99649': 17,
 '48626': 19,
 '90310': 20,
 '48629': 20,
 '90312': 20,
 '90313': 19,
 '82464': 20,
 '90315': 20,
 '90316': 19,
 '90317': 20,
 '90319': 20,
 '9099': 19,
 '97027': 20,
 '64776': 20,
 '91075': 17,
 '82442': 12,
 '51822': 19,
 '73168': 17,
 '96130': 19,
 '13059': 20,
 '13052': 11,
 '13053': 20,
 '13050': -31,
 '13051': 20,
 '13057': 18,
 '13054': 19,
 '13055': 18,
 '54171': 14,
 '54172': 20,
 '54173': 17,
 '54174': 20,
 '54175': 19,
 '54176': 17,
 '54177': 18,
 '94541': 16,
 '94540': 17,
 '94543': 19,
 '94542': 15,
 '94545': 17,
 '62088': 19,
 '94547': 15,
 '94546': 16,
 '62085': 20,
 '62084': 18,
 '62087': 20,
 '62086': 20,
 '62081': 20,
 '62080': 20,
 '62083': 20,
 '62082': 18,
 '20259': 20,
 '20252': 19,
 '20253': 20,
 '20250': 16,
 '20251': 15,
 '20256': 19,
 '11361': 20,
 '16882': 18,
 '20255': 20,
 '44427': 18,
 '44426': 19,
 '44425': 20,
 '29769': 4,
 '29768': 5,
 '40960': 20,
 '40961': 19,
 '29765': 9,
 '29764': 11,
 '29767': 7,
 '29766': 8,
 '29761': 14,
 '29760': 15,
 '29763': 12,
 '29762': 13,
 '1176': 20,
 '1173': 13,
 '1172': 14,
 '1171': 16,
 '1170': 18,
 '23507': 16,
 '23506': 19,
 '23505': 19,
 '23504': 20,
 '16883': 11,
 '23502': 18,
 '1179': 19,
 '1178': 20,
 '27619': 20,
 '27618': 14,
 '27617': 20,
 '27616': 19,
 '27615': 19,
 '27614': 16,
 '27613': 17,
 '27612': 18,
 '27611': 19,
 '27610': 20,
 '97939': 10,
 '97938': 11,
 '59038': 18,
 '59039': 18,
 '89370': 20,
 '59032': 2,
 '59033': 0,
 '59030': 5,
 '59031': 4,
 '59036': -3,
 '59037': -4,
 '59034': -1,
 '59035': -2,
 '32621': 20,
 '63792': 19,
 '28445': 19,
 '89371': 18,
 '65555': 20,
 '66128': 20,
 '12833': 20,
 '12831': 19,
 '66129': 19,
 '12837': 20,
 '8548': 18,
 '12835': 18,
 '12834': 19,
 '65880': 17,
 '65881': 20,
 '8547': 19,
 '8546': 20,
 '8541': 17,
 '8540': 18,
 '65886': 19,
 '23128': 20,
 '92262': 19,
 '92263': 20,
 '89372': 20,
 '92261': 20,
 '92266': 19,
 '92267': 18,
 '92264': 19,
 '92265': 20,
 '92268': 17,
 '92269': 16,
 '66504': 11,
 '66505': 9,
 '66506': 8,
 '66507': 7,
 '66500': 15,
 '66501': 14,
 '66502': 13,
 '66503': 12,
 '50413': 19,
 '50412': 20,
 '50411': 19,
 '50410': 20,
 '50417': 20,
 '23127': 18,
 '50415': 20,
 '50414': 19,
 '23126': 17,
 '88394': 20,
 '55623': 5,
 '66126': 15,
 '55621': 19,
 '55620': 20,
 '55627': 10,
 '55626': 18,
 '55625': 12,
 '66127': 20,
 '52811': 9,
 '52813': 17,
 '88396': 20,
 '66124': 6,
 '22678': 19,
 '22679': 18,
 '52818': 19,
 '22674': 19,
 '22675': 18,
 '22672': 19,
 '22673': 14,
 '22670': 17,
 '22671': 16,
 '15555': 15,
 '60900': 18,
 '60901': 20,
 '60906': 17,
 '82997': 20,
 '26568': 20,
 '26569': 20,
 '26566': 19,
 '26567': 18,
 '26564': 20,
 '26565': 19,
 '26562': 19,
 '15557': 10,
 '26560': 20,
 '26561': 20,
 '82999': 20,
 '15556': 12,
 '89747': 20,
 '82998': 19,
 '15551': 20,
 '85175': 19,
 '8294': 20,
 '75531': 18,
 '96699': 18,
 '75535': 20,
 '8297': 4,
 '75537': 16,
 '65264': 19,
 '65265': 19,
 '65266': 16,
 '48918': 19,
 '63793': 18,
 '101072': 19,
 '65263': 20,
 '68743': 19,
 '392': 18,
 '391': 19,
 '390': 20,
 '397': 19,
 '396': 9,
 '395': 20,
 '48916': 17,
 '59735': 19,
 '399': 8,
 '398': 10,
 '41069': 15,
 '54301': 20,
 '98280': 19,
 '48913': 20,
 '32225': 19,
 '32226': 20,
 '32227': 20,
 '32220': 20,
 '32221': 19,
 '32222': 20,
 '59738': 19,
 '93134': 20,
 '32228': 19,
 '32229': 20,
 '54300': 19,
 '93132': 19,
 '41067': 20,
 '7215': 18,
 '98108': 20,
 '3748': 2,
 '3749': 18,
 '3746': 17,
 '75286': 14,
 '3744': 20,
 '3745': 18,
 '3742': 19,
 '3743': 19,
 '3740': -12,
 '3741': 20,
 '97526': 20,
 '97749': 17,
 '73851': 18,
 '57661': 20,
 '57660': 19,
 '57663': 19,
 '57662': 20,
 '57665': 20,
 '57664': 20,
 '57667': 18,
 '57666': 19,
 '99850': 18,
 '57668': 17,
 '99855': 19,
 '99856': 17,
 '99857': 16,
 '69645': 19,
 '98640': 15,
 '99019': 19,
 '52103': 8,
 '52102': 9,
 '52101': 10,
 '52100': 11,
 '52107': 3,
 '52106': 4,
 '52105': 5,
 '52104': 6,
 '52108': 19,
 '78240': 19,
 '60018': 11,
 '60019': 18,
 '99015': 12,
 '96698': 19,
 '60015': 19,
 '60016': 19,
 '60017': 18,
 '60010': 17,
 '52979': 16,
 '99017': 18,
 '31163': 18,
 '102368': 18,
 '75968': 12,
 '78241': 20,
 '21930': 20,
 '21931': 20,
 '21932': 18,
 '21933': 20,
 '21934': 19,
 '21935': 18,
 '21936': 16,
 '21937': 16,
 '21938': 19,
 '21939': 20,
 '99013': 16,
 '99992': -11,
 '99995': 18,
 '93271': 16,
 '57085': -1,
 '57084': 0,
 '57087': 20,
 '57081': 4,
 '57080': 5,
 '57083': 1,
 '57082': 3,
 '24352': 18,
 '25281': 18,
 '57089': 20,
 '57088': 18,
 '75303': 8,
 '98849': 15,
 '29652': 5,
 '55837': 20,
 '55834': 19,
 '67498': 19,
 '100190': 11,
 '102372': 18,
 '19970': 19,
 '16709': 18,
 '59275': 20,
 '75300': 13,
 '16708': 20,
 '6819': -1,
 '6818': 0,
 '102364': 19,
 '80599': 20,
 '91954': 19,
 '6811': 10,
 '6810': 11,
 '6813': 7,
 '6812': 9,
 '6815': 5,
 '6814': 6,
 '6817': 2,
 '6816': 4,
 '9757': 16,
 '9756': 17,
 '9755': 18,
 '9754': 19,
 '9752': 18,
 '9750': 19,
 '91951': 20,
 '75301': 11,
 '9759': 13,
 '9758': 14,
 '24146': 19,
 '24147': 20,
 '24144': 20,
 '16706': 18,
 '37300': 20,
 '37301': 19,
 '24140': 16,
 '58931': 17,
 '80593': 19,
 '37308': 19,
 '37309': 19,
 '24148': 19,
 '80592': 20,
 '55839': 16,
 '59959': 19,
 '59958': 20,
 '54279': 14,
 '59951': 20,
 '91959': 19,
 '59953': 20,
 '54278': 15,
 '59955': 20,
 '59954': 19,
 '59957': 17,
 '59956': 20,
 '37076': 17,
 '37077': 16,
 '96331': 19,
 '33755': 20,
 '65368': 19,
 '11844': 12,
 '10515': 20,
 '54273': 20,
 '37073': 19,
 '68348': 20,
 '33751': 20,
 '68344': 20,
 '68345': 19,
 '68346': 18,
 '37071': 16,
 '68340': 12,
 '68341': 20,
 '68342': 18,
 '102106': -1,
 '88028': 20,
 '93149': 20,
 '67379': 20,
 '67374': 19,
 '67375': 18,
 '67376': 20,
 '67377': 18,
 '67088': 20,
 '67371': 20,
 '67372': 19,
 '67373': 20,
 '102105': 0,
 '91825': 19,
 '99777': 14,
 '64674': 18,
 '88987': 11,
 '68882': 19,
 '102100': 6,
 '52469': 19,
 '97802': 18,
 '100014': 19,
 '23328': 18,
 '30334': 20,
 '15160': 19,
 '30336': 8,
 '30337': 20,
 '30330': 13,
 '30331': 12,
 '30332': 11,
 '15161': 20,
 '76167': 20,
 '100012': 18,
 '76165': 20,
 '88983': 15,
 '15162': 20,
 '76161': 17,
 '76160': 19,
 '7566': 19,
 '15163': 20,
 '44804': 20,
 '15164': 20,
 '43059': 20,
 '7564': 16,
 '15165': 19,
 '7565': 20,
 '15166': 18,
 '98110': 20,
 '44801': 20,
 '30221': 16,
 '69299': 20,
 '44800': 20,
 '72394': 16,
 '72395': 15,
 '72396': 12,
 '102413': 20,
 '72390': 12,
 '72391': 20,
 '72392': 20,
 '72393': 18,
 '64678': 13,
 '44802': 19,
 '10250': 20,
 '72399': 20,
 '64679': 20,
 '91218': 11,
 '91219': 10,
 '88553': 20,
 '91213': 17,
 '91210': 20,
 '52467': 19,
 '91216': 13,
 '91217': 12,
 '91214': 15,
 '53143': 20,
 '72548': 20,
 '35219': 19,
 '53563': 12,
 '35214': 16,
 '35215': 20,
 '35216': 19,
 '35217': 17,
 '35210': 20,
 '53739': 15,
 '35212': 20,
 '35213': 19,
 '23266': 20,
 '23267': 19,
 '23264': 18,
 '23265': 17,
 '23262': 20,
 '23263': 19,
 '23260': 20,
 '23261': 19,
 '101709': 20,
 '86930': 17,
 '23268': 18,
 '23269': 19,
 '87901': 19,
 '24586': 4,
 '67089': 20,
 '87902': 20,
 '87905': 20,
 '87907': 16,
 '87906': 17,
 '63023': 20,
 '94331': 20,
 '66156': 20,
 '9256': 18,
 '92643': 18,
 '88551': 20,
 '29670': 20,
 '10702': 20,
 '24582': 18,
 '53731': 20,
 '43859': 19,
 '10700': 17,
 '72833': 20,
 '43853': 17,
 '10707': 20,
 '43851': 18,
 '43850': 19,
 '43855': 13,
 '10706': 17,
 '96669': 19,
 '88550': 20,
 '10705': 18,
 '9251': 19,
 '75145': 20,
 '6778': 19,
 '6779': 18,
 '6774': 19,
 '6775': 18,
 '6776': 14,
 '6777': 20,
 '6770': 20,
 '6771': 19,
 '6772': 20,
 '6773': 20,
 '88557': 16,
 '92744': 20,
 '69298': 19,
 '73444': 20,
 '73443': 18,
 '73442': 19,
 '73441': 20,
 '73440': 19,
 '46797': 19,
 '24375': 17,
 '93961': 19,
 '44662': 19,
 '55208': 19,
 '96333': 19,
 '93848': 18,
 '86505': -34,
 '61477': 18,
 '81569': 19,
 '49565': 19,
 '89343': 20,
 '61476': 19,
 '49564': 20,
 '46799': 20,
 '100334': 17,
 '46798': 17,
 '89504': 20,
 '98595': 19,
 '49561': 18,
 '88555': 20,
 '21610': 20,
 '55201': 18,
 '49563': 20,
 '75148': 19,
 '84221': 19,
 '49562': 20,
 '84220': 20,
 '55202': 17,
 '55205': 20,
 '55204': 20,
 '68880': 20,
 '90257': 19,
 '55207': 20,
 '75149': 19,
 '18580': 19,
 '84229': 15,
 '81999': 20,
 '24371': 20,
 '49167': 18,
 '81990': 18,
 '81991': 17,
 '81992': 16,
 '81993': 15,
 '81995': 8,
 '81997': 20,
 '42810': 16,
 '42811': 15,
 '42812': 20,
 '42813': 20,
 '42814': 17,
 '42815': -16,
 '42816': 20,
 '42817': 19,
 '42818': 20,
 '85670': 20,
 '85673': 20,
 '58461': 20,
 '85675': 20,
 '85674': 19,
 '85677': 20,
 '5058': 17,
 '5059': 18,
 '5054': 10,
 '5055': 20,
 '5056': 19,
 '5057': 18,
 '5050': 16,
 '5051': 13,
 '5052': 17,
 '5053': 20,
 '96660': 20,
 '88671': 19,
 '69171': 17,
 '75887': 19,
 '38560': 20,
 '38563': 19,
 '38562': 18,
 '38565': 19,
 '38564': 20,
 '96749': 7,
 '38566': 18,
 '72542': 19,
 '25956': 20,
 '53561': 14,
 '18585': 19,
 '100363': 20,
 '70134': 20,
 '70135': 20,
 '70132': 19,
 '70133': 18,
 '70130': 12,
 '70131': 20,
 '18893': 18,
 '18892': 19,
 '18891': 20,
 '18890': 19,
 '18897': 19,
 '18896': 15,
 '18895': 16,
 '18894': 17,
 '18899': 20,
 '18898': 14,
 '96748': 8,
 '24372': 20,
 '88534': 20,
 '48128': 12,
 '69178': 20,
 '94134': 20,
 '88562': 20,
 '13892': 18,
 '69838': 18,
 '87299': 19,
 '87298': 20,
 '98495': 18,
 '64809': 20,
 '87290': 19,
 '87293': 19,
 '87292': 20,
 '87295': 20,
 '87294': 20,
 '87297': 18,
 '87296': 20,
 '44221': 18,
 '44220': 19,
 '44223': 16,
 '44222': 17,
 '36178': 19,
 '36179': 18,
 '44227': 20,
 '44226': 13,
 '44229': 19,
 '44228': 20,
 '36177': 20,
 '36170': 14,
 '64805': 20,
 '36173': 19,
 '18769': 17,
 '18768': 20,
 '89948': 19,
 '33529': 20,
 '18761': 17,
 '33525': 18,
 '33526': 17,
 '18762': 18,
 '18765': 16,
 '18764': 19,
 '18767': 19,
 '18766': 20,
 '41543': 20,
 '41542': 19,
 '41541': 20,
 '41540': 20,
 '41547': 20,
 '41546': 16,
 '41545': 17,
 '41544': 20,
 '8535': 19,
 '41549': 19,
 '64800': 17,
 '87168': 19,
 '87129': 15,
 '87128': 16,
 '83637': 19,
 '83636': 20,
 '83635': 20,
 '83634': 20,
 '71747': 19,
 '72546': 19,
 '94137': 19,
 '1519': 19,
 '94985': 20,
 '44790': 20,
 '38873': 3,
 '8746': 20,
 '75886': 20,
 '91680': 19,
 '70665': 19,
 '52381': 19,
 '96290': 20,
 '44796': 16,
 '54066': 19,
 '53733': 20,
 '71777': 18,
 '79442': 16,
 '71772': 15,
 '71771': 16,
 '71770': 18,
 '98490': 15,
 '96298': 20,
 '71779': 20,
 '58078': 11,
 '8035': 20,
 '8034': 18,
 '8037': 19,
 '8036': 20,
 '8031': 16,
 '8030': 18,
 '8033': 19,
 '8032': 20,
 '48167': 20,
 '8039': 20,
 '8038': 18,
 '76208': 20,
 '14746': 19,
 '93847': 19,
 '46861': 20,
 '12589': 18,
 '12588': 20,
 '38870': 8,
 '46860': 15,
 '12583': 20,
 '12582': -38,
 '12580': 20,
 '12587': 19,
 '12586': 19,
 '12585': 20,
 '44913': 19,
 '44912': 19,
 '44911': 19,
 '44910': 20,
 '44917': 18,
 '44916': 19,
 '44915': 20,
 '44914': 17,
 '95960': 11,
 '58071': 20,
 '44919': 16,
 '44918': 17,
 '95964': 20,
 '79444': 14,
 '73332': 18,
 '94676': 18,
 '89490': 20,
 '89493': 20,
 '79793': 7,
 '89495': 14,
 '58073': 20,
 '89496': 18,
 '89499': 17,
 '18343': 20,
 '46180': 19,
 '76074': 20,
 '48120': 20,
 '88721': 20,
 '53024': 20,
 '88723': 18,
 '88724': 17,
 '88725': 20,
 '65068': 20,
 '88727': 20,
 '65066': 8,
 '65067': 7,
 '65064': 10,
 '65065': 9,
 '65062': 13,
 ...}

In [291]:
train_order = dict()
for session in train_data['viewed'].values:
    idx = 20
    for product in session.split(','):
        if product not in train_order:
            train_order[product] = idx
            idx -= 1

In [293]:
test_order = dict()
for session in test_data['viewed'].values:
    idx = 20
    for product in session.split(','):
        if product not in test_order:
            test_order[product] = idx
            idx -= 1

In [157]:
sorted_test_viewed = []
sorted_test_purchased = []
for idx in test_data.dropna()['viewed'].values:
    sorted_test_viewed.append(sorted(set(idx.split(',')), key=lambda idx: viewed[idx], reverse=True))
    sorted_test_purchased.append(sorted(set(idx.split(',')), key=lambda idx: purchased[idx], reverse=True))

In [16]:
def precision_k(sorted_list, data, k):
    answer_list = []
    for viewed, purchased in zip(sorted_list, data.dropna()['purchased'].values):
        res = len(set(viewed[:k]) & set(purchased.split(','))) / k
        answer_list.append(res)
    return round(np.mean(answer_list), 2)

In [23]:
def recall_k(sorted_list, data, k):
    answer_list = []
    for viewed, purchased in zip(sorted_list, data.dropna()['purchased'].values):
        res = len(set(viewed[:k]) & set(purchased.split(','))) / len(purchased.split(','))
        answer_list.append(res)
    return round(np.mean(answer_list), 2)

In [178]:
def write_answer_to_file(answer, filename):
    with open(filename, 'w') as f_out:
        f_out.write(' '.join(str(num) for num in answer))

In [158]:
answer_1 = recall_k(sorted_train_viewed, train_data, k=1), precision_k(sorted_train_viewed, train_data, k=1), \
           recall_k(sorted_train_viewed, train_data, k=5), precision_k(sorted_train_viewed, train_data, k=5)

In [159]:
answer_2 = recall_k(sorted_test_viewed, test_data, k=1), precision_k(sorted_test_viewed, test_data, k=1), \
           recall_k(sorted_test_viewed, test_data, k=5), precision_k(sorted_test_viewed, test_data, k=5)

In [324]:
answer_3 = recall_k(sorted_train_purchased, train_data, k=1), precision_k(sorted_train_purchased, train_data, k=1), \
           recall_k(sorted_train_purchased, train_data, k=5), precision_k(sorted_train_purchased, train_data, k=5)

In [374]:
answer_4 = recall_k(sorted_test_purchased, test_data, k=1), precision_k(sorted_test_purchased, test_data, k=1), \
           recall_k(sorted_test_purchased, test_data, k=5), precision_k(sorted_test_purchased, test_data, k=5)

In [299]:
sorted_train_purchased[1]

['85', '93', '86', '84', '87', '88', '89', '90', '91', '92']

In [375]:
answer_4

(0.43, 0.49, 0.8, 0.2)

In [367]:
purchased['546']

0

In [363]:
sorted_test_purchased[6]

['544', '545', '543', '546']

In [346]:
test_data.dropna()

,viewed,purchased
7,"63,68,69,70,66,61,59,61,66,68","66,63"
14,"158,159,160,159,161,162",162
19,"200,201,202,203,204","201,205"
34,"371,372,371","371,373"
40,422,422
47,"463,465,466,465,19,467,464,468,469,470,471,472...","462,460"
57,"543,544,545,546",543
94,"900,894,904,894,902,904,905,906,895,894,901,89...",904
115,1063,1063
125,"1119,1120,1121,1122,1123,1124,1125,1126,1123,1...",1126
129,"1174,500,1175,1176,1177,500,1175,1176",1174
137,"1257,1258,1259,1260,1261,1260,1262,1263,1262,1...","1258,1265"
140,"161,162,551,1278,551,1278,1279,1245,1280,1281,...",1283
148,"1328,1334,1335,1336",1337
154,1374,1374
174,1493,1493
183,1563,1563
194,"1658,1657",1658
197,"1673,1674,1675,1676,1677,1678,1679,1680,1681,1...",1673
209,"1090,1091,1788",1091
213,"343,170",170
228,"1916,1917,1916,1918,1919,1920,1916,1921,1922",1916
230,"1939,1940,1941,141,1207,1942,1943,1942,1932,19...","1940,1207,1932,1942,1949,1939"
271,"2314,2315,2314,2315,2316,2315,2314,2315,2314",2314
283,"2414,2415,2414,2416,2417,2418,2419",2414
289,"2462,297",297
293,"2478,2479,2480",2480
308,"2571,2572",2572
327,"2707,2708,2709",2708
331,"2733,2734,2733",2733
...,...,...
49645,"10374,3003",3003
49663,"27621,27622,27621",27621
49669,"83217,4717,83217,102466,90508,90506,90507,8321...",90508
49672,"102468,101594,102469,102468,101594","102468,101594,102469"
49674,"91026,30875,30595,98866,30595,98866,30595,7073...","56766,91026,102481,70730,30595"
49675,"8620,8433,102484,30875,30595,1275,88667,84008,...","56766,51344,30875,51343,51342,84008,30595,8636..."
49713,11160,11160
49736,"1770,918",1770
49759,"25189,40868,102549,25189",25189
49774,"102558,102559,102560,102561",17476
49792,"17378,17379,17378,102572,17378,17379,17378",17378
49817,"63450,24177,39693,101241,102587,39302,20823,24177",24177
49819,"11416,5984,42273,14131,65051,14131","5984,14131"
49825,"61624,57592,61624,57592","61624,57592"
49829,9623,9623
49841,"102598,26104,12372,78012,102598,26519,12372,26...","102598,26519,91997,12372"
49851,"102606,20809,6698",102606
49864,"10406,52777,102613",102613
49877,"3845,25337,63013,88191,6455,37815,15533,3846,1...","1346,88191"
49879,"15144,17636",17636
49882,"7596,19658,27228,1592,11497,28490,102625,23316...",18853
49892,63432,63432
49911,"17019,17405,36005,17019",17019
49937,"19224,2205,19224,2205",19224
49940,"65149,66733,65149",65149
49943,"2859,2854,88887,96997,4439,28645,99975,34601,1...","24907,102691,18496,4333"
49944,"77655,23249,1306,47450,26157,58205,47450,58205...","58205,3111,69482"
49945,"60538,44430,66252,44430,60538,66251","66252,44430"
49946,"49815,76363",49815
49985,"21841,17711,21841,17711,21841,17711,21841,1771...",21841

In [340]:
write_answer_to_file(answer_1, 'views_popularity_train.txt')
write_answer_to_file(answer_2, 'views_popularity_test.txt')
write_answer_to_file(answer_3, 'purchases_popularity_train.txt')
write_answer_to_file(answer_4, 'purchases_popularity_test.txt')